title: Eliuz Koyi Osongo
logo: assets/img/Untitled design (3)-modified.png
description: Currently transitioning into back-end development, with a strong focus on Python, SQL, and Django for building robust APIs. Gained hands-on experience in developing and deploying scalable back-end web systems.
show_downloads: false
theme: jekyll-theme-minimal
