title: Eliuz Koyi Osongo
logo: assets/img/Untitled design (3)-modified.png
description: Presently transitioning into back-end development with skills in Python and Django for APIs. Seamlessly managed this change/transition to master database management using SQL, develop and deploy back-end web systems 
show_downloads: false
theme: jekyll-theme-minimal
